In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('users.csv')
df1 = pd.read_csv('cards.csv')
df2 = pd.read_csv('trans.csv')
df3 = pd.read_csv('fraud.csv')
df4 = pd.read_csv('segmentation.csv')
df5 = pd.read_csv('recommendations.csv')

In [3]:
df.head()

,Person,Current Age,Retirement Age,Birth Year,Birth Month,Gender,Address,Apartment,City,State,Zipcode,Latitude,Longitude,Per Capita Income - Zipcode,Yearly Income - Person,Total Debt,FICO Score,Num Credit Cards
0,Hazel Robinson,53,66,1966,11,Female,462 Rose Lane,NaN,La Verne,CA,91750,34.15,-117.76,$29278,$59696,$127613,787,5
1,Sasha Sadr,53,68,1966,12,Female,3606 Federal Boulevard,NaN,Little Neck,NY,11363,40.76,-73.74,$37891,$77254,$191349,701,5
2,Saanvi Lee,81,67,1938,11,Female,766 Third Drive,NaN,West Covina,CA,91792,34.02,-117.89,$22681,$33483,$196,698,5
3,Everlee Clark,63,63,1957,1,Female,3 Madison Street,NaN,New York,NY,10069,40.71,-73.99,$163145,$249925,$202328,722,4
4,Kyle Peterson,43,70,1976,9,Male,9620 Valley Stream Drive,NaN,San Francisco,CA,94117,37.76,-122.44,$53797,$109687,$183855,675,1

In [4]:
df.columns

Index(['Person', 'Current Age', 'Retirement Age', 'Birth Year', 'Birth Month',
       'Gender', 'Address', 'Apartment', 'City', 'State', 'Zipcode',
       'Latitude', 'Longitude', 'Per Capita Income - Zipcode',
       'Yearly Income - Person', 'Total Debt', 'FICO Score',
       'Num Credit Cards'],
      dtype='object')

In [5]:
df1.head()

,User,CARD INDEX,Card Brand,Card Type,Card Number,Expires,CVV,Has Chip,Cards Issued,Credit Limit,Acct Open Date,Year PIN last Changed,Card on Dark Web
0,0,0,Visa,Debit,4344676511950444,12/2022,623,YES,2,$24295,09/2002,2008,No
1,0,1,Visa,Debit,4956965974959986,12/2020,393,YES,2,$21968,04/2014,2014,No
2,0,2,Visa,Debit,4582313478255491,02/2024,719,YES,2,$46414,07/2003,2004,No
3,0,3,Visa,Credit,4879494103069057,08/2024,693,NO,1,$12400,01/2003,2012,No
4,0,4,Mastercard,Debit (Prepaid),5722874738736011,03/2009,75,YES,1,$28,09/2008,2009,No

In [6]:
df1.columns

Index(['User', 'CARD INDEX', 'Card Brand', 'Card Type', 'Card Number',
       'Expires', 'CVV', 'Has Chip', 'Cards Issued', 'Credit Limit',
       'Acct Open Date', 'Year PIN last Changed', 'Card on Dark Web'],
      dtype='object')

In [7]:
df2.head()

,User,Card,Year,Month,Day,Time,Amount,Use Chip,Merchant Name,Merchant City,Merchant State,Zip,MCC,Errors?,Is Fraud?
0,0,0,2002,9,1,06:21,$134.09,Swipe Transaction,3527213246127876953,La Verne,CA,91750.0,5300,NaN,No
1,0,0,2002,9,1,06:42,$38.48,Swipe Transaction,-727612092139916043,Monterey Park,CA,91754.0,5411,NaN,No
2,0,0,2002,9,2,06:22,$120.34,Swipe Transaction,-727612092139916043,Monterey Park,CA,91754.0,5411,NaN,No
3,0,0,2002,9,2,17:45,$128.95,Swipe Transaction,3414527459579106770,Monterey Park,CA,91754.0,5651,NaN,No
4,0,0,2002,9,3,06:23,$104.71,Swipe Transaction,5817218446178736267,La Verne,CA,91750.0,5912,NaN,No

In [8]:
df2.columns

Index(['User', 'Card', 'Year', 'Month', 'Day', 'Time', 'Amount', 'Use Chip',
       'Merchant Name', 'Merchant City', 'Merchant State', 'Zip', 'MCC',
       'Errors?', 'Is Fraud?'],
      dtype='object')

In [9]:
df3.head()

,User,Merchant Name,Year,Month,Day,Time,is_new_merchant_for_user,is_new_mcc_for_user,tx_count_24h,time_since_prev_tx,amount_vs_user_median,Is Fraud?,fraud_score,fraud_band,fraud_action
0,0,1913477460590765860,2017,5,15,06:19,0,1,3.0,73740.0,2.262394,0,0.001149,Medium,Monitor
1,0,-34551508091458520,2017,5,15,06:38,0,1,2.0,1140.0,1.197183,0,0.001175,Low,Approve
2,0,-86825621511712373,2017,5,15,10:49,0,1,3.0,15060.0,0.369499,0,0.001060,High,OTP
3,0,-727612092139916043,2017,5,16,06:30,0,1,3.0,70860.0,0.532535,0,0.001044,Critical,Decline
4,0,4060646732831064559,2017,5,18,06:17,0,0,3.0,172020.0,1.772817,0,0.001130,Medium,Monitor

In [10]:
df3.columns

Index(['User', 'Merchant Name', 'Year', 'Month', 'Day', 'Time',
       'is_new_merchant_for_user', 'is_new_mcc_for_user', 'tx_count_24h',
       'time_since_prev_tx', 'amount_vs_user_median', 'Is Fraud?',
       'fraud_score', 'fraud_band', 'fraud_action'],
      dtype='object')

In [11]:
df4.head()

,User,txn_count,total_spend,avg_txn_amount,spend_cv,category_entropy,share_Groceries,share_Dining_Food,share_Transport_Fuel,share_Retail_Apparel,...,share_Digital_Subscriptions,share_Travel_Lodging,share_Entertainment_Leisure,num_cards,total_credit_limit,avg_credit_limit,avg_fraud_score,pct_high,pct_critical,cluster
0,0,19963,1622991.69,81.299989,1.158169,2.034541,0.177282,0.054720,0.072794,0.228775,...,0.052263,0.045376,0.004553,5,105105.0,21021.0,0.001225,0.224658,0.187823,3
1,1,8919,723491.89,81.118050,1.932797,1.803725,0.047638,0.084613,0.034325,0.157945,...,0.035937,0.118453,0.004946,5,65183.0,13036.6,0.001495,0.216283,0.437539,0
2,2,41978,1475933.36,35.159687,1.544341,1.448890,0.057180,0.026455,0.114227,0.021171,...,0.046968,0.041401,0.017608,5,133340.0,26668.0,0.001350,0.178442,0.280064,1
3,3,10117,1186497.51,117.277603,2.290757,1.830075,0.071181,0.117604,0.016303,0.043833,...,0.053597,0.188017,0.002924,4,356324.0,89081.0,0.001433,0.239575,0.311938,2
4,4,18542,1798790.91,97.011698,1.428895,1.609290,0.070531,0.020382,0.014073,0.197707,...,0.034227,0.078048,0.002327,1,34900.0,34900.0,0.001207,0.147194,0.324366,6

In [12]:
df4.columns

Index(['User', 'txn_count', 'total_spend', 'avg_txn_amount', 'spend_cv',
       'category_entropy', 'share_Groceries', 'share_Dining_Food',
       'share_Transport_Fuel', 'share_Retail_Apparel',
       'share_Healthcare_Wellness', 'share_Utilities_Bills',
       'share_Digital_Subscriptions', 'share_Travel_Lodging',
       'share_Entertainment_Leisure', 'num_cards', 'total_credit_limit',
       'avg_credit_limit', 'avg_fraud_score', 'pct_high', 'pct_critical',
       'cluster'],
      dtype='object')

In [13]:
df5.head()

,user_id,cluster,rank,card_id,card_name,brand,card_tier,annual_fee,apr,final_score,cluster_id,persona
0,0,3.0,1,C3_AMEX_1,Amex Platinum Elite,Amex,premium,550,16.9,7418.508853,3,Affluent Multi-Category Spenders
1,0,3.0,2,C1_AMEX_1,Amex Drive Gold,Amex,premium,150,17.9,7407.975136,1,Affluent Multi-Category Spenders
2,0,3.0,3,C0_AMEX_1,Amex Blue Retail,Amex,cashback,0,17.9,7405.837430,0,Affluent Multi-Category Spenders
3,1,0.0,1,C0_VISA_2,Visa Lifestyle Plus,Visa,lifestyle,95,18.5,3298.505698,0,Retail-Centric Lifestyle Spenders
4,1,0.0,2,C0_MC_1,MC Urban Life,Mastercard,lifestyle,79,18.9,3297.573270,0,Retail-Centric Lifestyle Spenders

In [20]:
df5.columns

Index(['user_id', 'cluster', 'rank', 'card_id', 'card_name', 'brand',
       'card_tier', 'annual_fee', 'apr', 'final_score', 'cluster_id',
       'persona'],
      dtype='object')

In [17]:
df6 = pd.read_csv('card_master_table.csv')

In [18]:
df6.head()

,card_id,card_name,brand,cluster_id,min_fico,max_fico,annual_fee,apr,credit_limit_min,credit_limit_max,reward_grocery,reward_dining,reward_fuel,reward_travel,reward_retail,reward_digital,reward_other,card_tier
0,C0_VISA_1,Visa Everyday Rewards,Visa,0,660,740,0,19.9,2000,6000,1,2,1,1,3,2,1,cashback
1,C0_VISA_2,Visa Lifestyle Plus,Visa,0,700,780,95,18.5,8000,15000,2,3,1,2,3,2,1,lifestyle
2,C0_MC_1,MC Urban Life,Mastercard,0,690,760,79,18.9,7000,12000,1,3,1,2,3,2,1,lifestyle
3,C0_AMEX_1,Amex Blue Retail,Amex,0,700,800,0,17.9,5000,10000,2,2,1,1,3,2,1,cashback
4,C0_DISC_1,Discover Retail It,Discover,0,660,740,0,20.9,2000,5000,1,2,1,1,5,1,1,cashback

In [19]:
df6.columns

Index(['card_id', 'card_name', 'brand', 'cluster_id', 'min_fico', 'max_fico',
       'annual_fee', 'apr', 'credit_limit_min', 'credit_limit_max',
       'reward_grocery', 'reward_dining', 'reward_fuel', 'reward_travel',
       'reward_retail', 'reward_digital', 'reward_other', 'card_tier'],
      dtype='object')